services:
  {{SERVICE_NAME}}:
{{SOURCE}}
    container_name: {{SERVICE_NAME}}
    restart: unless-stopped
    networks:
      proxy:
        aliases:
          - {{SERVICE_NAME}}

networks:
  proxy:
    external: true
